version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data # creates persistent storage point
    environment:
       POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 300 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000" # exposes containers port 3000 to native OS
    depends_on:
      - db